title: Azure DevOps to GitHub Migration – <CUSTOMER>
description: Migration documentation for <CUSTOMER> – Azure DevOps to GitHub Enterprise Cloud
theme: just-the-docs

url: <GITHUB_PAGES_URL>

aux_links:
  Migration Repository: <MIGRATION_REPO_URL>

# Front matter defaults
defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"
